# Generated by Django 5.1.6 on 2025-02-08 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laguna', '0003_reservation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('time_slot', models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('21:00', '21:00')], help_text='Selecione o horário fixo (hh:mm)', max_length=5)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguna.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
