# Generated by Django 4.2.19 on 2025-02-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laguna', '0007_customuser_is_member_customuser_membership_paid_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='membership_paid_date',
            new_name='membership_venc_date',
        ),
    ]
