# Generated by Django 4.2.19 on 2025-02-22 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laguna', '0008_rename_membership_paid_date_customuser_membership_venc_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao_debito', 'Cartão Débito'), ('cartao_credito', 'Cartão Crédito'), ('fiado', 'Fiado')], max_length=20)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguna.modalidade')),
                ('usuario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
